# Generated by Django 2.0.4 on 2018-07-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='ldap_attribute_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
