# Generated by Django 2.0.4 on 2018-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eav', '0002_attribute_ldap_attribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='ldap_attribute_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
